//* Lista de juegos
const GAMES = [
  { id: "Texans vs Bills", home: "Texans", away: "Bills" },
  { id: "Bears vs Steelers", home: "Bears", away: "Steelers" },
  { id: "Bengals vs Patriots", home: "Bengals", away: "Patriots" },
  { id: "Lions vs Giants", home: "Lions", away: "Giants" },
  { id: "Packers vs Vikings", home: "Packers", away: "Vikings" },
  { id: "Titans vs Seahawks", home: "Titans", away: "Seahawks" },
  { id: "Chiefs vs Colts", home: "Chiefs", away: "Colts" },
  { id: "Ravens vs Jets", home: "Ravens", away: "Jets" },
  { id: "Raiders vs Browns", home: "Raiders", away: "Browns" },
  { id: "Cardinals vs Jaguars", home: "Cardinals", away: "Jaguars" },
  { id: "Cowboys vs Eagles", home: "Cowboys", away: "Eagles" },
  { id: "Saints vs Falcons", home: "Saints", away: "Falcons" },
  { id: "Rams vs Buccaneers", home: "Rams", away: "Buccaneers" },
  { id: "49ers vs Panthers", home: "49ers", away: "Panthers" }
];

//! Logos de equipos
const TEAM_LOGOS = {
  "Cowboys":"https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
  "Giants":"https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
  "Eagles":"https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
  "Commanders":"https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
  "Chiefs":"https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
  "Broncos":"https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
  "Dolphins":"https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
  "Jets":"https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
  "49ers":"https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
  "Seahawks":"https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
  "Bengals":"https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
  "Steelers":"https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
  "Bills":"https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
  "Patriots":"https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
  "Rams":"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
  "Cardinals":"https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
  "Falcons":"https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
  "Browns":"https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
  "Lions":"https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
  "Panthers":"https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
  "Chargers":"https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
  "Buccaneers":"https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
  "Saints":"https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
  "Vikings":"https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
  "Titans":"https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
  "Colts":"https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
  "Jaguars":"https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
  "Ravens":"https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
  "Bears":"https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
  "Raiders":"https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
  "Packers":"https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
  "Texans":"https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"
};