// Lista de juegos (ejemplo)
const GAMES = [
  { id: "Raiders vs Broncos", away: "Raiders", home: "Broncos" },
  { id: "Falcons vs Colts", away: "Falcons", home: "Colts" },
  { id: "Browns vs Jets", away: "Browns", home: "Jets" },
  { id: "Saints vs Panthers", away: "Saints", home: "Panthers" },
  { id: "Patriots vs Buccaneers", away: "Patriots", home: "Buccaneers" },
  { id: "Giants vs Bears", away: "Giants", home: "Bears" },
  { id: "Bills vs Dolphins", away: "Bills", home: "Dolphins" },
  { id: "Ravens vs Vikings", away: "Ravens", home: "Vikings" },
  { id: "Jaguars vs Texans", away: "Jaguars", home: "Texans" },
  { id: "Cardinals vs Seahawks", away: "Cardinals", home: "Seahawks" },
  { id: "Rams vs 49ers", away: "Rams", home: "49ers" },
  { id: "Lions vs Commanders", away: "Lions", home: "Commanders" },
  { id: "Steelers vs Chargers", away: "Steelers", home: "Chargers" },
  { id: "Eagles vs Packers", away: "Eagles", home: "Packers" }
];

const TEAM_LOGOS = {
  "Cowboys":"https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
  "Giants":"https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
  "Eagles":"https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
  "Commanders":"https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
  "Chiefs":"https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
  "Broncos":"https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
  "Dolphins":"https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
  "Jets":"https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
  "49ers":"https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
  "Seahawks":"https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
  "Bengals":"https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
  "Steelers":"https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
  "Bills":"https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
  "Patriots":"https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
  "Rams":"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
  "Cardinals":"https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
  "Falcons":"https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
  "Browns":"https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
  "Lions":"https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
  "Panthers":"https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
  "Chargers":"https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
  "Buccaneers":"https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
  "Saints":"https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
  "Vikings":"https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
  "Titans":"https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
  "Colts":"https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
  "Jaguars":"https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
  "Ravens":"https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
  "Bears":"https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
  "Raiders":"https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
  "Packers":"https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
  "Texans":"https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"
};