//* Lista de juegos
const GAMES = [
  { id: "Commanders vs Cowboys", home: "Commanders", away: "Cowboys" },
  { id: "Vikings vs Lions", home: "Vikings", away: "Lions" },
  { id: "Chiefs vs Broncos", home: "Chiefs", away: "Broncos" },
  { id: "Chargers vs Texans", home: "Chargers", away: "Texans" },
  { id: "Packers vs Ravens", home: "Packers", away: "Ravens" },
  { id: "Bengals vs Cardinals", home: "Bengals", away: "Cardinals" },
  { id: "Browns vs Steelers", home: "Browns", away: "Steelers" },
  { id: "Titans vs Saints", home: "Titans", away: "Saints" },
  { id: "Colts vs Jaguars", home: "Colts", away: "Jaguars" },
  { id: "Dolphins vs Buccaneers", home: "Dolphins", away: "Buccaneers" },
  { id: "Jets vs Patriots", home: "Jets", away: "Patriots" },
  { id: "Panthers vs Seahawks", home: "Panthers", away: "Seahawks" },
  { id: "Raiders vs Giants", home: "Raiders", away: "Giants" },
  { id: "Bills vs Eagles", home: "Bills", away: "Eagles" }, 
  { id: "49ers vs Bears", home: "49ers", away: "Bears" },
  { id: "Falcons vs Rams", home: "Falcons", away: "Rams" },
];

//! Logos de equipos
const TEAM_LOGOS = {
  "Cowboys":"https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
  "Giants":"https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
  "Eagles":"https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
  "Commanders":"https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
  "Chiefs":"https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
  "Broncos":"https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
  "Dolphins":"https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
  "Jets":"https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
  "49ers":"https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
  "Seahawks":"https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
  "Bengals":"https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
  "Steelers":"https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
  "Bills":"https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
  "Patriots":"https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
  "Rams":"https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
  "Cardinals":"https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
  "Falcons":"https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
  "Browns":"https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
  "Lions":"https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
  "Panthers":"https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
  "Chargers":"https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
  "Buccaneers":"https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
  "Saints":"https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
  "Vikings":"https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
  "Titans":"https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
  "Colts":"https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
  "Jaguars":"https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
  "Ravens":"https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
  "Bears":"https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
  "Raiders":"https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
  "Packers":"https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
  "Texans":"https://a.espncdn.com/i/teamlogos/nfl/500/hou.png"
};